compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

plugins:
  - checksum: ab1fb9e957fa4becd3787c784379934f25097957bb26201845b8aae48bc6229bba41a6df4316c475643585f2432541956a6e7f9697b10255182f36d354cac0af
    path: .yarn/plugins/@yarnpkg/plugin-tsconfig-references.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-tsconfig-references.js'

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.1.1.cjs
